name: 'Terraform'

on:
  push:
    branches: [ "teat1-branch" ]
  pull_request:
    branches: [ "test1-branch" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Terraform Plan
      run: terraform plan -out=tfplan -input=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: tfplan

  manual-approval:
    name: 'Manual Approval and Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Manual Approval
      run: |
        echo "Waiting for manual approval..."
        while true; do
          echo "Approve this job in the GitHub UI to proceed."
          sleep 60
        done
      if: ${{ github.event_name == 'workflow_dispatch' }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Terraform Plan
      uses: actions/download-artifact@v3
      with:
        name: terraform-plan

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -input=false tfplan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
